#!/usr/bin/env bash

set -euo pipefail

help() {
	cat <<-EOF >&2
		Usage: $0 [-h] <tag>
	EOF
}

options=$(getopt -n "$0" -o h -l help -- "$@")

if test $? -ne 0; then
	exit 1
fi

eval set -- "$options"

while :; do
	case "$1" in
		-h|--help)
			help
			exit
			;;
		--)
			shift
			break
			;;
	esac
done

if test -z "$*"; then
	echo "$0: missing argument, try --help for more information" >&2
	exit 1
fi

if ! git rev-parse "$1" >/dev/null 2>&1; then
    echo "$0: '$1' is not a valid tag" >&2
    exit 1
fi

platform="$(echo "$1" | cut -f1 -d/)"
name="$(echo "$1" | cut -f2 -d/)"
version="$(echo "$1" | cut -f3 -d/)"
filename="$name-$version-$platform"

export RELEASE="$name $version ($platform)"

mkdir -p dist

git archive --format=zip -o "dist/$filename.zip" --prefix="$name/" "$1:$platform/$name/"
scripts/changelog "$1" | grep "#[0-9]\+" > "dist/$filename.md"
