#!/usr/bin/env bash

# Sane defaults.
set -euo pipefail

# Find scripts directory.
script="$0"
if test -L "$script"; then
	script="$(readlink -f "$0")"
fi
prefix="$(dirname "$script")"
script="$(basename "$script")"

# Print the manual.
help() {
	cat <<-EOF >&2
		About
		        Bump add-on version in its manifest and commit.

		Usage
		        $script -h
		        $script [-x] <path>

		Flags
		        -h      Print this manual.
		        -x      Enable debug mode.
	EOF
}

# Parse and apply flags.
while getopts ":xh" option; do
	case "$option" in
		x)
			set -x
			;;
		h)
			help
			exit
			;;
		?)
			echo "$script: unknown flag '$OPTARG', try -h" >&2
			exit
			;;
	esac
done

# Drop flags by shifting arguments.
shift $((OPTIND - 1))

# Test required arguments.
if test -z "$*"; then
	echo "$script: missing required argument, see -h" >&2
	exit
fi

# Add-on directory path, e.g. ./Add-on.
target="$1"

# Validate target.
"$prefix/inspect" -V "$target"

# Name of the add-on, e.g. Add-on.
name="$("$prefix/inspect" -n "$target")"

# Version, e.g. 42.
version="$("$prefix/inspect" -v "$target")"

# Change version in ToC files.
find "$target" -type f -name "*.toc" -exec sed -i "s/## Version: .\+/## Version: $((version + 1))/" {} \;

# Commit the change.
git commit -m "Bump $name to v$((version + 1))" "$target/*.toc"
