#!/usr/bin/env bash

#
# Generate dist/CHANGELOG.md based off of given Git tag.
#

set -euo pipefail

help() {
	cat <<-EOF >&2
		Usage: $0 [-h] <tag>
	EOF
}

opts=$(getopt -n "$0" -o h -l help -- "$@")

if test $? -ne 0; then
	exit 1
fi

eval set -- "$opts"

while :; do
	case "$1" in
		-h|--help)
			help
			exit
			;;
		--)
			shift
			break
			;;
	esac
done

if test -z "$*"; then
	echo "$0: missing argument, try --help for more information" >&2
	exit 1
fi

tag="$1"

if ! git rev-parse "$tag" >/dev/null 2>&1; then
    echo "$0: '$tag' is not a valid tag" >&2
    exit 1
fi

prefix="${tag%/*}"
range="$(git describe --abbrev=0 --match "$prefix/*" -- "$tag^" 2>/dev/null | cut -f1 -d-)..$tag^"

# Distributable directory, e.g. ./dist.
dist="$target/dist"

mkdir -p "$dist"

git log --format="- %h %s" "${range#..}" -- "$prefix" | grep "#[0-9]\+" > "dist/CHANGELOG.md"
