#!/usr/bin/env bash

#
# Lint Lua and XML files recursively in a given directory.
#

set -euo pipefail

if test -z "$*"; then
    echo "$0: missing argument. e.g. $0 <path>" >&2
    exit 1
fi

target="$1"

if ! test -d "$target"; then
    echo "$target is not a directory." >&2
    exit 1
fi

platform="$(scripts/inspect --platform "$target")"

find "$target" -name "*.lua" -exec luacheck {} +
find "$target" -name "*.xml" -exec xmllint --noout --schema "$platform/UI.xsd" {} +
