#!/usr/bin/env bash

set -euo pipefail

help() {
	cat <<-EOF >&2
		Usage: $0 [-h|-m] <path>
	EOF
}

options=$(getopt -n "$0" -o hm -l help,manifest -- "$@")

if test $? -ne 0; then
	exit 1
fi

eval set -- "$options"

while :; do
	case "$1" in
		-m|--manifest)
			mode="manifest"
			shift
			;;
		-h|--help)
			help
			exit
			;;
		--)
			shift
			break
			;;
	esac
done

if test -z "$*"; then
	echo "$0: missing argument, try --help for more information" >&2
	exit 1
fi

if test -f "$1"; then
	path="$1"
else
	path="${1%/}"
fi

while test ! "$path" = "." -o "$path" = "/"; do
	manifest="$path/$(basename "$path").toc"

	if test -f "$manifest"; then
		case "${mode=directory}" in
			directory)
				echo "$path"
				;;
			manifest)
				echo "$manifest"
				;;
		esac

		exit
	fi

	path="$(dirname "$path")"
done

exit 1