#!/usr/bin/env bash

set -euo pipefail

help() {
	cat <<-EOF >&2
		Usage: $0 [-h|-p|-m|-M] <path>
	EOF
}

last-tagged-commit() {
	git rev-list --tags --no-walk -- "$1" | head -1 2>/dev/null
}

commits-since-last-tagged-commit() {
	git rev-list "$(last-tagged-commit "$1")..HEAD" -- "$1" 2>/dev/null
}

changelog() {
	git log --oneline "$(last-tagged-commit "$1")..HEAD" -- "$1" | grep "#[0-9]+" 2>/dev/null
}

options=$(getopt -n "$0" -o hpmM -l help,patch,minor,major -- "$@")

if test $? -ne 0; then
	exit 1
fi

eval set -- "$options"

while :; do
	case "$1" in
		-p|--patch)
			mode="patch"
			shift
			;;
		-m|--minor)
			mode="minor"
			shift
			;;
		-M|--major)
			mode="major"
			shift
			;;
		-h|--help)
			help
			exit
			;;
		--)
			shift
			break
			;;
	esac
done

if test -z "$*"; then
	echo "$0: missing argument, try --help for more information" >&2
	exit 1
fi

if ! test -d "$1"; then
	echo "$0: '$1' is not a directory" >&2
	exit 1
fi

platform="$(dirname "$1")"
name="$(basename "$1")"
manifest="$platform/$name/$name.toc"

if ! test -f "$manifest"; then
	echo "$0: '$manifest' is not a file" >&2
	exit 1
fi

old_version="$(grep -Po "Version: \K.+" "$manifest")"

major="$(echo "$old_version" | cut -f1 -d.)"
minor="$(echo "$old_version" | cut -f2 -d.)"
patch="$(echo "$old_version" | cut -f3 -d.)"

case "${mode=patch}" in
	patch)
		patch=$(commits-since-last-tagged-commit "$platform/$name" | wc -l)
		;;
	minor)
		patch=0
		minor=$((minor + 1))
		;;
	major)
		patch=0
		minor=0
		major=$((major + 1))
		;;
esac

new_version="$major.$minor.$patch"

if test "$old_version" = "$new_version"; then
	echo "$0: aborting, versions are identical" >&2
	exit 1
fi

sed -i "s/Version: $old_version/Version: $new_version/" "$manifest"

git commit -m "Bump $platform/$name to $new_version" "$manifest"

cat <<-EOF | git tag -F - "$platform/$name/$new_version"
	$name $new_version ($platform)

	$(changelog "$(dirname "$manifest")")
EOF

git push --follow-tags
