#!/usr/bin/env bash

set -eu

if test -z "$*"; then
    $0 classic retail
    exit 0
fi

test-lua() {
    luacheck --no-global --no-max-line-length "$1" || echo
}

test-xml() {
    xmllint --schema UI.xsd $(find $1 -name '*.xml') --noout || echo 
}

for argument in "$@"; do
    target="$(realpath $argument)"

    if ! test -d "$target"; then
        echo "$target is not a directory." >&2
        exit 1
    fi

    test-xml "$target"
    test-lua "$target"
done