#!/usr/bin/env bash

set -euo pipefail

if test -z "$*"; then
    $0 classic retail
    exit 0
fi

test-lua() {
    luacheck --no-global --no-max-line-length "$1"
}

test-xml() {
    xmllint --schema UI.xsd $(find "$1" -name '*.xml') --noout
}

failed=0

for argument in "$@"; do
    subject="$(realpath $argument)"

    if ! test -d "$subject"; then
        echo "$subject is not a directory." >&2
        exit 1
    fi

    if ! test-xml "$subject"; then
        failed=1
    fi
    if ! test-lua "$subject"; then
        failed=1
    fi
done

exit $failed