#!/usr/bin/env bash

#
# Upload archive to CurseForge.
#

set -euo pipefail

help() {
	cat <<-EOF >&2
		Usage: $0 [-h]|-t <token> <tag>
	EOF
}

opts=$(getopt -n "$0" -o ht: -l help,token: -- "$@")

if test $? -ne 0; then
	exit 1
fi

eval set -- "$opts"

while :; do
	case "$1" in
		-h|--help)
			help
			exit
			;;
		-t|--token)
			token="$2"
			shift 2
			;;
		--)
			shift
			break
			;;
	esac
done

tag="$1"
target="$(scripts/parse "$tag")"

if ! test -f "$target/.curseforge"; then
	echo "$0: '$target/.curseforge' is not a file" >&2
	exit 1
fi

archive="$(scripts/inspect -a "$target")"

if ! test -f "dist/$archive"; then
	echo "$0: dist/$archive is not a file" >&2
	exit 1
fi

project_id="$(jq .projectId "$target/.curseforge")"

# `$changelog` here is a jq variable.
jq --rawfile changelog dist/CHANGELOG.md '.changelog = $changelog | del(.projectId)' .curseforge \
	| jq -r tostring > metadata.json

curl -vf -X POST "https://wow.curseforge.com/api/projects/$project_id/upload-file" \
	-H "X-Api-Token: $token" \
	-F "metadata=@metadata.json" \
	-F "file=@dist/$archive"
