#!/usr/bin/env bash

set -euo pipefail

if test -z "$*"; then
    echo "Missing argument. e.g. $0 <directory>" >&2
    exit 1
fi

for argument in "$@"; do
    subject="$(realpath $argument)"

    if ! test -d "$subject"; then
        echo "$subject is not a directory." >&2
        exit 1
    fi

    xmllint --schema UI.xsd $(find "$1" -name "*.xml") --noout
done
