#!/usr/bin/env bash

set -euo pipefail

if test -z "$*"; then
    echo "$0: missing argument. e.g. $0 <directory>..." >&2
    exit 1
fi

for arg in "$@"; do
    directory="$(realpath $arg)"

    if ! test -d "$directory"; then
        echo "$directory is not a directory." >&2
        exit 1
    fi

    find "$directory" -name "*.xml" -exec xmllint --noout --schema UI.xsd {} +
done
