name: Release

on:
  push:
    tags:
      - "*/*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils lua-check
          version: 1
      - name: Export environment
        run: scripts/env -x "$GITHUB_REF" >> "$GITHUB_ENV"
      - name: Lint source files
        run: scripts/lint -x "$TARGET"
      - name: Generate archive
        run: scripts/archive -x "$TAG"
      - name: Generate changelog
        run: scripts/changelog -x "$TAG"
      - name: Upload to GitHub
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ env.TARGET }}/dist/CHANGELOG.md
          files: ${{ env.TARGET }}/dist/*.zip
          tag_name: ${{ env.TAG }}
          draft: false
          name: ${{ env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to CurseForge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: scripts/upload -xt "$CURSEFORGE_TOKEN" "$TAG"
