name: Release add-on

on:
  push:
    tags:
      - "*/*/*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: source scripts/env

      - name: Install dependencies
        run: sudo apt-get install libxml2-utils lua-check

      - name: Lint source files
        run: scripts/lint "$TARGET"

      - name: Generate package and changelog
        run: scripts/package "$TAG"
        run: scripts/changelog "$TAG"

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          body_path: dist/CHANGELOG.md
          files: dist/*.zip
          tag_name: ${{ env.TAG }}
          draft: false
          name: ${{ env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
